version: "3.1"

services:
  db:
    container_name: database
    image: mysql:5.7
    command: --init-file /docker-entrypoint.initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: gorgonzola
    volumes:
      - ./sqls:/docker-entrypoint.initdb.d
    networks:
      - shared_network
    ports:
      - "3306:3306"
  data_service:
    container_name: data_service
    depends_on:
      - db
    image: rest-o-matic:mysql-5.7
    command: xmysql -h db -u root -p root -d gorgonzola -r 0.0.0.0
    restart: always
    networks:
      - shared_network
    ports:
      - "3000:3000"
networks:
  shared_network:
